development:
  adapter: postgresql
  encoding: utf8
  database: final_project_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: final_project_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: final_project_app
  pool: 5
